In [3]:
import autograd.numpy as np
from autograd import grad, jacobian

x = np.array([5,3], dtype=float)

def cost(x):
    return x[0]**2 / x[1] - np.log(x[1])
def derev_1(x):
    return x[0]*2 / x[1] - np.log(x[1])

gradient_cost = grad(cost)
jacobian_cost = jacobian(cost)

gradient_cost(x)
jacobian_cost(np.array([x,x,x]))

array([[[ 2.        ,  0.        ],
        [-1.2       ,  0.        ],
        [ 0.        ,  0.        ]],

       [[ 0.        ,  2.        ],
        [ 0.        , -1.33333333],
        [ 0.        ,  0.        ]]])

In [4]:
x

array([5., 3.])

In [5]:
cost(np.array([x,x,x]))

array([3.39056209, 1.90138771])

In [6]:
derev_1(np.array([x,x,x]))

array([0.39056209, 0.90138771])

In [7]:
np.array([x,x,x])[0]

array([5., 3.])

In [8]:
from sympy import sin, cos, Matrix
from sympy.abc import rho, phi
X = Matrix([rho*cos(phi), rho*sin(phi), rho**2])
Y = Matrix([rho, phi])
X.jacobian(Y)


Matrix([
[cos(phi), -rho*sin(phi)],
[sin(phi),  rho*cos(phi)],
[   2*rho,             0]])

In [9]:
# Matrix([
# [cos(phi), -rho*sin(phi)],
# [sin(phi),  rho*cos(phi)],
# [   2*rho,             0]])
X = Matrix([rho*cos(phi), rho*sin(phi)])
X.jacobian(Y)

Matrix([
[cos(phi), -rho*sin(phi)],
[sin(phi),  rho*cos(phi)]])

In [19]:
from sympy import MatrixSymbol
from sympy.abc import T,C
X = MatrixSymbol('X', 3, 1)
Y = MatrixSymbol('Y', 3, 1) 
theta = MatrixSymbol('theta', 3, 1) 
# two columns are teb states
# last is enemy

poses = Matrix([[X,Y,theta]]).T
poses


Matrix([
[    X[0, 0],     X[1, 0],     X[2, 0]],
[    Y[0, 0],     Y[1, 0],     Y[2, 0]],
[theta[0, 0], theta[1, 0], theta[2, 0]]])

In [11]:
poses.shape[0]

2

In [20]:
import sympy
middle_pose = poses[:,0:2] * sympy.ones(poses.shape[1]-1,1)/2
# middle_pose = middle_pose[0:2,:]
middle_pose


Matrix([
[        X[0, 0]/2 + X[1, 0]/2],
[        Y[0, 0]/2 + Y[1, 0]/2],
[theta[0, 0]/2 + theta[1, 0]/2]])

In [13]:
# middle_pose = Matrix[sympy.sum(poses[0,:])/2]
# middle_pose
2**2

4

In [21]:
from sympy import Matrix
dist_related_mat = Matrix([[middle_pose[0,0]-poses[0,2]],[middle_pose[1,0]-poses[1,2]]])
dist_related_mat


Matrix([
[X[0, 0]/2 + X[1, 0]/2 - X[2, 0]],
[Y[0, 0]/2 + Y[1, 0]/2 - Y[2, 0]]])

In [15]:
# sympy.Pow(middle_pose[0,1]-poses[1,2],2)

In [18]:
# dist_param = 1
from sympy import Matrix
error_mat = Matrix([[T*1/(C*((dist_related_mat[0,0])**2+(dist_related_mat[1,0])**2+1))]])
error_mat

Matrix([[T/(C*((X[0, 0]/2 + X[1, 0]/2 - X[2, 0])**2 + (Y[0, 0]/2 + Y[1, 0]/2 - Y[2, 0])**2 + 1))]])

In [23]:
target_points = Matrix([poses[:,0].T,poses[:,1].T])
target_points

Matrix([
[X[0, 0], Y[0, 0], theta[0, 0]],
[X[1, 0], Y[1, 0], theta[1, 0]]])

In [27]:
error_mat.jacobian(target_points[0,:])


Matrix([[T*(-X[0, 0]/2 - X[1, 0]/2 + X[2, 0])/(C*((X[0, 0]/2 + X[1, 0]/2 - X[2, 0])**2 + (Y[0, 0]/2 + Y[1, 0]/2 - Y[2, 0])**2 + 1)**2), T*(-Y[0, 0]/2 - Y[1, 0]/2 + Y[2, 0])/(C*((X[0, 0]/2 + X[1, 0]/2 - X[2, 0])**2 + (Y[0, 0]/2 + Y[1, 0]/2 - Y[2, 0])**2 + 1)**2), 0]])

In [28]:
error_mat.jacobian(target_points[1,:])

Matrix([[T*(-X[0, 0]/2 - X[1, 0]/2 + X[2, 0])/(C*((X[0, 0]/2 + X[1, 0]/2 - X[2, 0])**2 + (Y[0, 0]/2 + Y[1, 0]/2 - Y[2, 0])**2 + 1)**2), T*(-Y[0, 0]/2 - Y[1, 0]/2 + Y[2, 0])/(C*((X[0, 0]/2 + X[1, 0]/2 - X[2, 0])**2 + (Y[0, 0]/2 + Y[1, 0]/2 - Y[2, 0])**2 + 1)**2), 0]])

In [31]:
error_mat.jacobian(Matrix([T]))

Matrix([[1/(C*((X[0, 0]/2 + X[1, 0]/2 - X[2, 0])**2 + (Y[0, 0]/2 + Y[1, 0]/2 - Y[2, 0])**2 + 1))]])